# Generated by Django 3.1.2 on 2020-11-03 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('order', models.IntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cocktail_App.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.DecimalField(decimal_places=3, max_digits=5)),
                ('unit', models.CharField(choices=[('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('fl oz', 'fluid ounce'), ('cup', 'cup'), ('pint', 'pint'), ('quart', 'quart'), ('gallon', 'gallon'), ('ml', 'milliter'), ('l', 'liter'), ('lb', 'pound'), ('oz', 'ounce'), ('mg', 'milligram'), ('g', 'gram'), ('kg', 'kilogram'), ('dashes', 'dashes')], max_length=32, null=True)),
                ('note', models.CharField(max_length=32, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cocktail_App.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cocktail_App.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('parentType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cocktail_App.ingredienttype')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredientType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cocktail_App.ingredienttype'),
        ),
    ]
