# Generated by Django 3.1.2 on 2021-12-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cocktail_App', '0002_recipe_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='userId',
            new_name='user',
        ),
    ]
